name: CI (.net)

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test + Coverage
        run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory ./coverage
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v5
        with:
          name: coverage
          path: ./coverage

  report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v5
        with:
          name: coverage
      - name: Install report generator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
      - name: Generate report
        run: reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"./report" -reporttypes:"MarkdownSummaryGithub"
      - name: Write to Job Summary
        run: cat ./report/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
