using System.Text.Json;
using System.Text.Json.Serialization;

namespace PrivacyProxy.Api.Models.DTOs.LLM;

/// <summary>
/// Represents the response of a chat completion operation, including the unique identifier for the response,
/// a list of choices generated by the operation, and any additional extension data.
/// </summary>
public record ChatCompletionResponse
{
    /// <summary>
    /// Gets the unique identifier associated with the chat completion response.
    /// This identifier is provided by the server and is used to uniquely
    /// track the response within the context of the request.
    /// </summary>
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    /// <summary>
    /// Represents the list of choices in a chat completion response. Each choice is an instance
    /// of <see cref="ChatCompletionChoice"/> and contains information about a generated message
    /// and its associated metadata, such as the response message, finish reason, and any extension data.
    /// </summary>
    [JsonPropertyName("choices")]
    public required List<ChatCompletionChoice> Choices { get; init; }

    /// <summary>
    /// Represents additional data not explicitly defined by the properties of the
    /// corresponding object. This field can store key-value pairs of JSON elements
    /// that are dynamically included within the serialized JSON payload.
    /// </summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Extensions { get; init; }
}